### ISSUE TITLE
Continue from last played position

### ISSUE THREAD

**Issue by ozdefir** [ozdefir/oku-player#1]
Hi Firat,

I'm trying to add a "remember last played postion" feature to my web app, and here is my plan:
1. The logAudioEvent function keeps a detailed information on the last played position, so I will add a few lines of codes to send these log back to server in JSON format. 
2. When the user visit the same page next time, my front end will load the user's log history, and determine what is his/her last played TIME. 
3. Set the audio start time to be the last played time, so that when user click the PLAY button, it resume playing at the last position.

So my question is, how to set the audio start time to a specific postion? Where should I put the relevant code into the Okuplayer.js? 

Thanks!

(He ZHANG)

**Comment by ozdefir** [comment]
Hi He,
I think instead of the last play time, the last fragment number would be more useful in your case. You don't have to make a change to okuplayer.js for that. To play a certain fragment you can do this after starting the instance:
`okuPlayerInstance.playFragment(26)
`
By the way, I thought of keeping the user settings in a cookie but I think it's best to leave it to the application. 

You're the first person to test it outside readiance.org. I would be very interested to know how it goes.

@storyweaver

**Comment by storyweaver** [comment]
Hi Firat.
Thank you for your reply.
I tried by adding `okuPlayerInstance.playFragment(26) ;` after `var okuPlayerInstance = new OkuPlayer(okuConfig);`

Got the following error:

 okuplayer.js:443  Uncaught TypeError: Cannot read property 'element' of undefined

`this.currentFragment.element.className` = "fragm";`  

Sample code:
`...
    var okuConfig = {
        "xhtmlPath":"29s.xhtml",
        "syncmapPath":"29s.json",
        "audioPaths":["29.mp3","29.ogg"],
        "meta":{
            "book":"The Adventures of Tom Sawyer",
            "author":"Mark Twain",
            "chapter":"Chapter 29",
            "chapterAuthor":"",
            "info":"Read by Piotr Nater for LibriVox",
            "toc":"/the-adventures-of-tom-sawyer-by-mark-twain",
            "fullscreen":"/play/the-adventures-of-tom-sawyer-dramatic-reading-by-mark-twain/chapter-29"
        },
        "settings":{
            "continuous":true,
            "autoscroll":true,
            "pagedView":true
        }
    };

var okuPlayerInstance = new OkuPlayer(okuConfig);
okuPlayerInstance.playFragment(26) ;

....`

**Comment by ozdefir** [comment]
Hi,
I added a configuration option to choose the first fragment to play **okuConfig.setting.startFrom** like so :

```
.....
"settings":{
"continuous":true,
"autoscroll":true,
"pagedView":true,
"startFrom":26
}
....
```

You can also set it with the URL hash #OkuStart{Fragment Index}: https://readiance.org/OkuPlayer/demo/demo.html#OkuStart20

It seems to work fine with Chrome, Firefox and IE 11 on Windows 7.  Let me know how it goes for you.
